apiVersion: apps/v1
kind: Deployment
metadata:
    name: yunwei-test
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: myapp
    template:
        metadata:
            labels:
                app: myapp
        spec:
            containers:
            - image: 10.1.24.102/yunwei:latest
              imagePullPolicy: IfNotPresent 
              name: yunwei-test
---
apiVersion: v1
kind: Service
metadata:
  name: yunwei
spec:
  selector:
    app: myapp
  ports:
  - name: web
    port: 80
    targetPort: 60000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-yunwei-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: yunwei-test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: yunwei
          servicePort: 80
